"""Added test table

Revision ID: 4bf19b09a82f
Revises: 
Create Date: 2020-12-08 14:50:25.972750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf19b09a82f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test1',
    sa.Column('test2', sa.String(), nullable=True),
    sa.Column('test3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('test3')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
